<?php
if (!defined('FM_SECURITY')) die();

class header
{
	public  static $headers = array (
		'Cache-Control'       => array('no-cache, must-revalidate',false),
		'Content-Encoding'    => array(null,false),
		'Content-Language'    => array(null,false),
		'Content-Location'    => array(null,false),
		'Content-Disposition' => array(null,false),
		'Content-Type'        => array('text/html; charset=utf-8',false),
		'Expires'             => array(null,false),
		'Last-Modified'       => array(null,false),
		'Location'            => array(null,false),
		'Pragma'              => array('no-cache',false),
		'Status'              => array(200,false),
		'WWW-Authenticate'    => array(null,false),
		'X-Generator'         => array(null,false),
	);
	
	public  static $mimeCodes = array (
		'acx'     => 'application/internet-property-stream',
		'ai'      => 'application/postscript',
		'aif'     => 'audio/x-aiff',
		'aifc'    => 'audio/x-aiff',
		'aiff'    => 'audio/x-aiff',
		'arj'     => 'application/x-arj-compressed',
		'asc'     => 'text/plain',
		'asf'     => 'video/x-ms-asf',
		'asr'     => 'video/x-ms-asf',
		'asx'     => 'video/x-ms-asx',
		'au'      => 'audio/ulaw',
		'avi'     => 'video/x-msvideo',
		'axs'     => 'application/olescript',
		'bas'     => 'text/plain',
		'bat'     => 'application/x-msdos-program',
		'bcpio'   => 'application/x-bcpio',
		'bin'     => 'application/octet-stream',
		'bmp'     => 'image/bmp',
		'c'       => 'text/plain',
		'cat'     => 'application/vnd.ms-pkiseccat',
		'cc'      => 'text/plain',
		'ccad'    => 'application/clariscad',
		'cdf'     => 'application/x-netcdf',
		'cer'     => 'application/x-x509-ca-cert',
		'class'   => 'application/octet-stream',
		'clp'     => 'application/x-msclip',
		'cmx'     => 'image/x-cmx',
		'cod'     => 'application/vnd.rim.cod',
		'com'     => 'application/x-msdos-program',
		'cpio'    => 'application/x-cpio',
		'cpt'     => 'application/mac-compactpro',
		'crd'     => 'application/x-mscardfile',
		'crl'     => 'application/pkix-crl',
		'crt'     => 'application/x-x509-ca-cert',
		'csh'     => 'application/x-csh',
		'css'     => 'text/css',
		'dcr'     => 'application/x-director',
		'deb'     => 'application/x-debian-package',
		'der'     => 'application/x-x509-ca-cert',
		'dir'     => 'application/x-director',
		'djv'     => 'image/vnd.djvu',
		'djvu'    => 'image/vnd.djvu',
		'dl'      => 'video/dl',
		'dll'     => 'application/octet-stream',
		'dms'     => 'application/octet-stream',
		'doc'     => 'application/msword',
		'dot'     => 'application/msword',
		'drw'     => 'application/drafting',
		'dvi'     => 'application/x-dvi',
		'dwg'     => 'application/acad',
		'dxf'     => 'application/dxf',
		'dxr'     => 'application/x-director',
		'eps'     => 'application/postscript',
		'etx'     => 'text/x-setext',
		'evy'     => 'application/envoy',
		'exe'     => 'application/x-msdos-program',
		'ez'      => 'application/andrew-inset',
		'f'       => 'text/plain',
		'f90'     => 'text/plain',
		'fif'     => 'application/fractals',
		'fli'     => 'video/x-fli',
		'flr'     => 'x-world/x-vrml',
		'flv'     => 'video/flv',
		'gif'     => 'image/gif',
		'gl'      => 'video/gl',
		'gtar'    => 'application/x-gtar',
		'gz'      => 'application/x-gzip',
		'h'       => 'text/plain',
		'hdf'     => 'application/x-hdf',
		'hh'      => 'text/plain',
		'hlp'     => 'application/winhlp',
		'hqx'     => 'application/mac-binhex40',
		'hta'     => 'application/hta',
		'htc'     => 'text/x-component',
		'htm'     => 'text/html',
		'html'    => 'text/html',
		'htt'     => 'text/webviewhtml',
		'ice'     => 'x-conference/x-cooltalk',
		'ico'     => 'image/x-icon',
		'ief'     => 'image/ief',
		'iges'    => 'model/iges',
		'igs'     => 'model/iges',
		'iii'     => 'application/x-iphone',
		'ins'     => 'application/x-internet-signup',
		'ips'     => 'application/x-ipscript',
		'ipx'     => 'application/x-ipix',
		'isp'     => 'application/x-internet-signup',
		'jad'     => 'text/vnd.sun.j2me.app-descriptor',
		'jar'     => 'application/java-archive',
		'jfif'    => 'image/pipeg',
		'jpe'     => 'image/jpeg',
		'jpeg'    => 'image/jpeg',
		'jpg'     => 'image/jpeg',
		'js'      => 'application/x-javascript',
		'json'    => 'application/json',
		'kar'     => 'audio/midi',
		'latex'   => 'application/x-latex',
		'lha'     => 'application/octet-stream',
		'lsf'     => 'video/x-la-asf',
		'lsp'     => 'application/x-lisp',
		'lsx'     => 'video/x-la-asf',
		'lzh'     => 'application/octet-stream',
		'm'       => 'text/plain',
		'm13'     => 'application/x-msmediaview',
		'm14'     => 'application/x-msmediaview',
		'm3u'     => 'audio/x-mpegurl',
		'man'     => 'application/x-troff-man',
		'mdb'     => 'application/x-msaccess',
		'me'      => 'application/x-troff-me',
		'mesh'    => 'model/mesh',
		'mht'     => 'message/rfc822',
		'mhtml'   => 'message/rfc822',
		'mid'     => 'audio/midi',
		'midi'    => 'audio/midi',
		'mif'     => 'application/x-mif',
		'mime'    => 'www/mime',
		'mny'     => 'application/x-msmoney',
		'mov'     => 'video/quicktime',
		'movie'   => 'video/x-sgi-movie',
		'mp2'     => 'video/mpeg',
		'mp3'     => 'audio/mpeg',
		'mp4'     => 'video/mp4',
		'mpa'     => 'video/mpeg',
		'mpe'     => 'video/mpeg',
		'mpeg'    => 'video/mpeg',
		'mpg'     => 'video/mpeg',
		'mpga'    => 'audio/mpeg',
		'mpp'     => 'application/vnd.ms-project',
		'mpv2'    => 'video/mpeg',
		'ms'      => 'application/x-troff-ms',
		'msh'     => 'model/mesh',
		'mvb'     => 'application/x-msmediaview',
		'mxu'     => 'video/vnd.mpegurl',
		'nc'      => 'application/x-netcdf',
		'nws'     => 'message/rfc822',
		'oda'     => 'application/oda',
		'ogg'     => 'application/ogg',
		'ogm'     => 'application/ogg',
		'p10'     => 'application/pkcs10',
		'p12'     => 'application/x-pkcs12',
		'p7b'     => 'application/x-pkcs7-certificates',
		'p7c'     => 'application/x-pkcs7-mime',
		'p7m'     => 'application/x-pkcs7-mime',
		'p7r'     => 'application/x-pkcs7-certreqresp',
		'p7s'     => 'application/x-pkcs7-signature',
		'pbm'     => 'image/x-portable-bitmap',
		'pdb'     => 'chemical/x-pdb',
		'pdf'     => 'application/pdf',
		'pfx'     => 'application/x-pkcs12',
		'pgm'     => 'image/x-portable-graymap',
		'pgn'     => 'application/x-chess-pgn',
		'pgp'     => 'application/pgp',
		'pko'     => 'application/ynd.ms-pkipko',
		'pl'      => 'application/x-perl',
		'pm'      => 'application/x-perl',
		'pma'     => 'application/x-perfmon',
		'pmc'     => 'application/x-perfmon',
		'pml'     => 'application/x-perfmon',
		'pmr'     => 'application/x-perfmon',
		'pmw'     => 'application/x-perfmon',
		'png'     => 'image/png',
		'pnm'     => 'image/x-portable-anymap',
		'pot'     => 'application/vnd.ms-powerpoint',
		'ppm'     => 'image/x-portable-pixmap',
		'pps'     => 'application/vnd.ms-powerpoint',
		'ppt'     => 'application/vnd.ms-powerpoint',
		'ppz'     => 'application/vnd.ms-powerpoint',
		'pre'     => 'application/x-freelance',
		'prf'     => 'application/pics-rules',
		'prt'     => 'application/pro_eng',
		'ps'      => 'application/postscript',
		'pub'     => 'application/x-mspublisher',
		'qt'      => 'video/quicktime',
		'ra'      => 'audio/x-realaudio',
		'ram'     => 'audio/x-pn-realaudio',
		'rar'     => 'application/x-rar-compressed',
		'ras'     => 'image/x-cmu-raster',
		'rgb'     => 'image/x-rgb',
		'rm'      => 'audio/x-pn-realaudio',
		'rmi'     => 'audio/mid',
		'roff'    => 'application/x-troff',
		'rpm'     => 'audio/x-pn-realaudio-plugin',
		'rtf'     => 'text/rtf',
		'rtx'     => 'text/richtext',
		'scd'     => 'application/x-msschedule',
		'scm'     => 'application/x-lotusscreencam',
		'sct'     => 'text/scriptlet',
		'set'     => 'application/set',
		'setpay'  => 'application/set-payment-initiation',
		'setreg'  => 'application/set-registration-initiation',
		'sgm'     => 'text/sgml',
		'sgml'    => 'text/sgml',
		'sh'      => 'application/x-sh',
		'shar'    => 'application/x-shar',
		'silo'    => 'model/mesh',
		'sit'     => 'application/x-stuffit',
		'skd'     => 'application/x-koan',
		'skm'     => 'application/x-koan',
		'skp'     => 'application/x-koan',
		'skt'     => 'application/x-koan',
		'smi'     => 'application/smil',
		'smil'    => 'application/smil',
		'snd'     => 'audio/basic',
		'so'      => 'application/octet-stream',
		'sol'     => 'application/solids',
		'spc'     => 'application/x-pkcs7-certificates',
		'spl'     => 'application/x-futuresplash',
		'src'     => 'application/x-wais-source',
		'sst'     => 'application/vnd.ms-pkicertstore',
		'step'    => 'application/step',
		'stl'     => 'application/sla',
		'stm'     => 'text/html',
		'stp'     => 'application/step',
		'sv4cpio' => 'application/x-sv4cpio',
		'sv4crc'  => 'application/x-sv4crc',
		'svg'     => 'image/svg+xml',
		'swf'     => 'application/x-shockwave-flash',
		't'       => 'application/x-troff',
		'tar'     => 'application/x-tar',
		'tar.gz'  => 'application/x-tar-gz',
		'tcl'     => 'application/x-tcl',
		'tex'     => 'application/x-tex',
		'texi'    => 'application/x-texinfo',
		'texinfo' => 'application/x-texinfo',
		'tgz'     => 'application/x-tar-gz',
		'tif'     => 'image/tiff',
		'tiff'    => 'image/tiff',
		'tr'      => 'application/x-troff',
		'trm'     => 'application/x-msterminal',
		'tsi'     => 'audio/tsp-audio',
		'tsp'     => 'application/dsptype',
		'tsv'     => 'text/tab-separated-values',
		'txt'     => 'text/plain',
		'uls'     => 'text/iuls',
		'unv'     => 'application/i-deas',
		'ustar'   => 'application/x-ustar',
		'vcd'     => 'application/x-cdlink',
		'vcf'     => 'text/x-vcard',
		'vda'     => 'application/vda',
		'viv'     => 'video/vnd.vivo',
		'vivo'    => 'video/vnd.vivo',
		'vrm'     => 'x-world/x-vrml',
		'vrml'    => 'x-world/x-vrml',
		'wav'     => 'audio/x-wav',
		'wax'     => 'audio/x-ms-wax',
		'wbmp'    => 'image/vnd.wap.wbmp',
		'wbxml'   => 'application/vnd.wap.wbxml',
		'wcm'     => 'application/vnd.ms-works',
		'wdb'     => 'application/vnd.ms-works',
		'wks'     => 'application/vnd.ms-works',
		'wma'     => 'audio/x-ms-wma',
		'wmf'     => 'application/x-msmetafile',
		'wml'     => 'text/vnd.wap.wml',
		'wmlc'    => 'application/vnd.wap.wmlc',
		'wmls'    => 'text/vnd.wap.wmlscript',
		'wmlsc'   => 'application/vnd.wap.wmlscriptc',
		'wmv'     => 'video/x-ms-wmv',
		'wmx'     => 'video/x-ms-wmx',
		'wps'     => 'application/vnd.ms-works',
		'wri'     => 'application/x-mswrite',
		'wrl'     => 'model/vrml',
		'wrz'     => 'x-world/x-vrml',
		'wvx'     => 'video/x-ms-wvx',
		'xaf'     => 'x-world/x-vrml',
		'xbm'     => 'image/x-xbitmap',
		'xht'     => 'application/xhtml+xml',
		'xhtml'   => 'application/xhtml+xml',
		'xla'     => 'application/vnd.ms-excel',
		'xlc'     => 'application/vnd.ms-excel',
		'xll'     => 'application/vnd.ms-excel',
		'xlm'     => 'application/vnd.ms-excel',
		'xls'     => 'application/vnd.ms-excel',
		'xlt'     => 'application/vnd.ms-excel',
		'xlw'     => 'application/vnd.ms-excel',
		'xml'     => 'text/xml',
		'xof'     => 'x-world/x-vrml',
		'xpm'     => 'image/x-xpixmap',
		'xsl'     => 'text/xml',
		'xwd'     => 'image/x-xwindowdump',
		'xyz'     => 'chemical/x-pdb',
		'z'       => 'application/x-compress',
		'zip'     => 'application/zip',
		'323'     => 'text/h323',
	);
	
	
	public  static $statusCodes = array(
		'100'=>'Continue',
		'101'=>'Switching Protocols',
		'200'=>'OK',
		'201'=>'Created',
		'202'=>'Accepted',
		'203'=>'Non-Authoritative Information',
		'204'=>'No Content',
		'205'=>'Reset Content',
		'206'=>'Partial Content',
		'300'=>'Multiple Choices',
		'301'=>'Moved Permanently',
		'302'=>'Found',
		'303'=>'See Other',
		'304'=>'Not Modified',
		'305'=>'Use Proxy',
		'307'=>'Temporary Redirect',
		'400'=>'Bad Request',
		'401'=>'Unauthorized',
		'402'=>'Payment Required',
		'403'=>'Forbidden',
		'404'=>'Not Found',
		'405'=>'Method Not Allowed',
		'406'=>'Not Acceptable',
		'407'=>'Proxy Authentication Required',
		'408'=>'Request Timeout',
		'409'=>'Conflict',
		'410'=>'Gone',
		'411'=>'Length Required',
		'412'=>'Precondition Failed',
		'413'=>'Request Entity Too Large',
		'414'=>'Request-URI Too Long',
		'415'=>'Unsupported Media Type',
		'416'=>'Requested Range Not Satisfiable',
		'417'=>'Expectation Failed',
		'500'=>'Internal Server Error',
		'501'=>'Not Implemented',
		'502'=>'Bad Gateway',
		'503'=>'Service Unavailable',
		'504'=>'Gateway Timeout',
		'505'=>'HTTP Version Not Supported',
	);
	
	static function set($key,$value = null,$lock = false)
	{
		if (array_key_exists($key,header::$headers) && !header::$headers[$key][1])
			header::$headers[$key] = array($value,$lock);
	}
	
	static function send($content = null)
	{		
		if (empty(header::$headers['X-Generator'][0]))
			header::set('X-Generator',config::$config['header']['generator']);
		
		if (class_exists('cache'))
		{
			header::set('Expires',gmdate("D, d M Y H:i:s",cache::$expire) . " GMT");
			header::set('Last-Modified',gmdate("D, d M Y H:i:s",cache::$lastUpdate) . " GMT");
		}
		
		if (empty(header::$headers['Content-Type'][0]))
			header::set('Content-Type','text/html; charset=utf-8');
			
		if (array_key_exists(header::$headers['Content-Type'][0],header::$mimeCodes))
			header::set('Content-Type',header::$mimeCodes[header::$headers['Content-Type'][0]]);
		
		if (array_key_exists('Status',header::$headers) && is_numeric(header::$headers['Status'][0]))
		{
			@header('x',true,header::$headers['Status'][0]);
			unset(header::$headers['Status']);
		}
		
		foreach (header::$headers as $key=>$header)
			if (!empty($header[0]))
				@header("$key: {$header[0]}");
	}
}